# Send prefix
set-option -g prefix C-a
unbind-key C-a

setw -g mode-keys vi # Navigation in copy mode
set -g mouse on

# Use Alt-arrow keys to switch panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Quick window selection with Alt+number (no prefix)
bind -n M-1 select-window -t :0
bind -n M-2 select-window -t :1
bind -n M-3 select-window -t :2
bind -n M-4 select-window -t :3
bind -n M-5 select-window -t :4
bind -n M-6 select-window -t :5
bind -n M-7 select-window -t :6
bind -n M-8 select-window -t :7
bind -n M-9 select-window -t :8

# Quick reload config
bind-key r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# display popup
bind-key y display-popup

# Set easier window split keys
bind-key v split-window -h
bind-key h split-window -v

# In copy mode, use vi keys
bind Enter copy-mode
bind -T copy-mode-vi Escape send -X cancel

# Wayland clipboard integration
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy && wl-paste -n | wl-copy -p"
#bind p run "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"

# Ubuntu/Mint Terminal settings & color supper
#set -g default-terminal "tmux-256color"
#set -ga terminal-overrides ",*256col*:Tc"
#set-option -sa terminal-overrides ",xterm*:Tc"

# Kitty Terminal settings & color support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",tmux-256color:RGB"
set -ga terminal-overrides ",xterm-kitty:RGB,kitty*:RGB"
set -g allow-passthrough on # Allow passthrough for better terminal compatibility

# vim:set ft=tmux:

# --> Catppuccin (Mocha)
set -ogq @thm_bg "#1e1e2e"
set -ogq @thm_fg "#cdd6f4"

# Colors
set -ogq @thm_rosewater "#f5e0dc"
set -ogq @thm_flamingo "#f2cdcd"
set -ogq @thm_rosewater "#f5e0dc"
set -ogq @thm_pink "#f5c2e7"
set -ogq @thm_mauve "#cba6f7"
set -ogq @thm_red "#f38ba8"
set -ogq @thm_maroon "#eba0ac"
set -ogq @thm_peach "#fab387"
set -ogq @thm_yellow "#f9e2af"
set -ogq @thm_green "#a6e3a1"
set -ogq @thm_teal "#94e2d5"
set -ogq @thm_sky "#89dceb"
set -ogq @thm_sapphire "#74c7ec"
set -ogq @thm_blue "#89b4fa"
set -ogq @thm_lavender "#b4befe"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#a6adc8"
set -ogq @thm_subtext_0 "#bac2de"
set -ogq @thm_overlay_2 "#9399b2"
set -ogq @thm_overlay_1 "#7f849c"
set -ogq @thm_overlay_0 "#6c7086"
set -ogq @thm_surface_2 "#585b70"
set -ogq @thm_surface_1 "#45475a"
set -ogq @thm_surface_0 "#313244"
set -ogq @thm_mantle "#181825"
set -ogq @thm_crust "#11111b"

set -sg escape-time 0
