-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- AUTOGENERATED HYPRLAND CONFIG.

-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.conf AND EDIT IT,

-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

-- hl.monitor({
--     output   = "",
--     mode     = "preferred",
--     position = "auto",
--     scale    = "auto",
-- })

-- -----------------------------------------------------

-- Monitor Layout

-- -----------------------------------------------------

-- -----------------------------------------------------

-- Monitor Configuration

-- -----------------------------------------------------

-- -----------------------------------------------------

-- Fixed/Persistent Workspace Bindings

-- -----------------------------------------------------

-- Bind and lock Workspaces 1-5 to the Dell (Left)

--workspace = 1, monitor:DP-1, default:true, persistent:true

--workspace = 2, monitor:DP-1, persistent:true

--

--# Bind and lock Workspaces 6-10 to the LG UltraGear (Right)

--workspace = 3, monitor:DP-2, persistent:true

-- hl.workspace_rule({
--     workspace = 1,
--     monitor = "desc:Dell Inc.DELL U2722D DKNP7P3",
--     is_default = true,
--     persistent = true,
-- })
-- 
-- -- Bind and lock Workspaces 6-10 to the LG UltraGear (Right)
-- 
-- hl.workspace_rule({
--     workspace = 2,
--     monitor = "desc:LG Electronics LG ULTRAGEAR 103NTFAJE699",
--     is_default = true,
--     persistent = true,
-- })
-- 
-- hl.workspace_rule({
--     workspace = 3,
--     monitor = "desc:LG Electronics LG ULTRAGEAR 103NTFAJE699",
--     persistent = true,
-- })
-- 
-- hl.workspace_rule({
--     workspace = 4,
--     monitor = "desc:LG Electronics LG ULTRAGEAR 103NTFAJE699",
--     persistent = true,
-- })
-- 
-- hl.workspace_rule({
--     workspace = 5,
--     monitor = "desc:LG Electronics LG ULTRAGEAR 103NTFAJE699",
--     persistent = true,
-- })
-- 
-- hl.workspace_rule({
--     workspace = 6,
--     monitor = "desc:LG Electronics LG ULTRAGEAR 103NTFAJE699",
--     persistent = true,
-- })

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"

--$fileManager = yazi

local menu = "fuzzel"

local lockscreen = "hyprlock"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal

-- exec-once = nm-applet &

-- exec-once = waybar & hyprpaper & firefox





--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 20,
        border_size = 2,
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
})

-- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]

-- windowrule = rounding 0, floating:0, onworkspace:w[tv1]

-- windowrule = bordersize 0, floating:0, onworkspace:f[1]

-- windowrule = rounding 0, floating:0, onworkspace:f[1]

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = 0,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true,
        -- If true disables the random hyprland logo / anime girl background. :(
        disable_splash_rendering = true,
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        kb_options = "caps:escape",
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures

hl.config({
    gestures = {
        --workspace_swipe = true
        --workspace_swipe_fingers = 3
    },
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

--bind = $mainMod SHIFT, Delete, exec, hyprctl keyword monitor "eDP-1, 2560x1600@60, 0x0, 2"

--bind = $mainMod SHIFT, Backspace, exec, hyprctl keyword monitor "eDP-1, disable"

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())

--bind = $mainMod, E, exec, $fileManager

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("fuzzel"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "T", hl.dsp.group.toggle())

-- dwindle

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "f9", hl.dsp.exec_cmd("grim-| swappy -f-"))

hl.bind(mainMod .. " + " .. "f9", hl.dsp.exec_cmd("grim -g \"$(slurp)\"-| swappy -f-"))

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("hyprpicker -a"))

hl.bind(mainMod .. " + " .. "TAB", hl.dsp.focus({ workspace = "previous" }))

-- Special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "W", hl.dsp.workspace.toggle_special("window"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.window.move({ workspace = "special:window" }))

-- Move and resize windows with mouse

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Resize windows

hl.bind(mainMod .. " + " .. "R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind(" + L", hl.dsp.resizeactive("20 0"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind(" + H", hl.dsp.resizeactive("-20 0"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind(" + K", hl.dsp.resizeactive("0 -20"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind(" + J", hl.dsp.resizeactive("0 20"))
    hl.bind("ESCAPE", hl.dsp.submap("reset"))
end)


-- Move windows with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))


-- Move focus with mainMod + vim keys

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Scroll through existing workspaces

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "L", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "H", hl.dsp.focus({ workspace = "e-1" }))

hl.bind("ALT" .. " + " .. "J", hl.dsp.exec_cmd("wtype -k Down"))

hl.bind("ALT" .. " + " .. "K", hl.dsp.exec_cmd("wtype -k Up"))

hl.bind("ALT" .. " + " .. "H", hl.dsp.exec_cmd("wtype -k Left"))

hl.bind("ALT" .. " + " .. "L", hl.dsp.exec_cmd("wtype -k Right"))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule

-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.

-- TODO: manual review: suppress_event = "maximize"

-- Fix some dragging issues with XWayland

-- TODO: manual review: nofocus = true

-- Change visuals

-- source = ./extra/lookNfeel.conf -> requires manual conversion
-- local lookNfeel = require("_.extra.lookNfeel")
-- TODO: convert ./extra/lookNfeel.conf to .lua and use require()

-- source = ./extra/mocha.conf -> requires manual conversion
-- local mocha = require("_.extra.mocha")
-- TODO: convert ./extra/mocha.conf to .lua and use require()

-- D-Bus Environment Update (Essential for Wayland/Systemd)


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprctl setcursor Adwaita 20")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
end)
